#encoding
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  port: 8088

  #error
  error:
    #?? ??? exception? ??? ????
    include-exception: true
    #?? ??? stacktrace ??? ??? ?
    include-stacktrace: always
    #???? ??? ?? ?? ??? ???? ??? ???? ?? ? ?
    whitelabel:
      enabled: false

#oracle
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: golf
    password: golf

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true